// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbThen2FprH7NHiiedZFXkLl4wUY5xxE0',
    appId: '1:150347777938:web:7c30dfdd0df359648b634b',
    messagingSenderId: '150347777938',
    projectId: 'tasktodo-3d1d4',
    authDomain: 'tasktodo-3d1d4.firebaseapp.com',
    storageBucket: 'tasktodo-3d1d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZQDvqtS4Q00Yodb4pMR9tG3R1r4SMGZs',
    appId: '1:150347777938:android:2748d7fef3682f708b634b',
    messagingSenderId: '150347777938',
    projectId: 'tasktodo-3d1d4',
    storageBucket: 'tasktodo-3d1d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe56W0ZS0Sa759WYyzzKU8PQX2K3-hFQ8',
    appId: '1:150347777938:ios:75e96f9b988df2f18b634b',
    messagingSenderId: '150347777938',
    projectId: 'tasktodo-3d1d4',
    storageBucket: 'tasktodo-3d1d4.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe56W0ZS0Sa759WYyzzKU8PQX2K3-hFQ8',
    appId: '1:150347777938:ios:8443fb5f82f5d72a8b634b',
    messagingSenderId: '150347777938',
    projectId: 'tasktodo-3d1d4',
    storageBucket: 'tasktodo-3d1d4.appspot.com',
    iosBundleId: 'com.example.flutterToDoList.RunnerTests',
  );
}
